[package]
name = "cache-patterns"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
divan = { package = "codspeed-divan-compat", version = "4.2.1" }

[[bench]]
name = "particle_simulation"
harness = false
